analyzer:
  errors:
    avoid_print: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: ignore

formatter:
  page_width: 120
  trailing_commas: preserve
