name: example
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.4
  dart_mappable: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
  flutter_lints: ^2.0.0
  flutter_crystalline: ^0.4.0
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.3.0

flutter:

  uses-material-design: true
