name: crystalline_project

command:
  bootstrap:
    runPubGetInParallel: true
  version:
    linkToCommits: false     # disables commit links in generated changelog

packages:
  - example
  - packages/**

# use flutter version set in .fvmrc for development and running melos scripts
scripts:
  all:
    run: |
      melos bs &&
      melos run test &&
      melos run format &&
      melos run analyze
    description: Run melos bootstrap, test, format & analyze in order

  format:
    run: |
      melos exec -c 1 -- \
        dart analyze .
    description: Run dart format in all packages

  analyze:
    run: |
      melos exec -c 1 -- \
        flutter analyze .
    description: Run dart analyze in all packages

  test:
    run: |
      melos exec --ignore="*example*" -c 1 -- flutter test --coverage
    description: Run all tests .

  gen:
    run: melos exec --scope="example" -c 1 -- dart run build_runner build
