name: crystalline_project

command:
  bootstrap:
    usePubspecOverrides: true

packages:
  - packages/**
  - example

# use flutter version set in .fvmrc for development and running melos scripts
scripts:
  all:
    run: |
      melos bs &&
      melos run test &&
      melos run format &&
      melos run analyze
    description: Run melos bootstrap, test, format & analyze in order

  format:
    run: |
      melos exec -c 1 -- \
        dart analyze .
    description: Run dart format in all packages

  analyze:
    run: |
      melos exec -c 1 -- \
        flutter analyze .
    description: Run dart analyze in all packages

  test:
    run: |
      melos exec --ignore="*example*" --ignore="*flutter_riverpod_crystalline*" -c 1 -- flutter test --coverage
    description: Run all tests .
