name: crystalline_project

command:
  bootstrap:
    usePubspecOverrides: true

packages:
  - packages/**
  - example

scripts:
  analyze:
    run: |
      melos exec -c 1 -- \
        flutter analyze .
    description: Run dart analyze in all packages

  test:
    run: melos exec -c 1 -- flutter test
    description: Run all tests .
