name: crystalline_project

command:
  bootstrap:
    runPubGetInParallel: true
  version:
    linkToCommits: false     # disables commit links in generated changelog

packages:
  - example
  - packages/**

# use flutter version set in .fvmrc for development and running melos scripts
scripts:
  all:
    run: |
      melos bs &&
      melos run test &&
      melos run format &&
      melos run check
    description: Run melos bootstrap, test, format & analyze in order

  format:
    run: melos exec -c 1 -- dart format lib test
    description: Run dart format in all packages

  check:
    run: melos exec --fail-fast --ignore="example" -- dart analyze .
    description: Run dart analyze in all packages

  test:
    run: melos exec  -c 1 --ignore="*example*" --ignore="crystalline_builder" -- flutter test --coverage
    description: Run all tests .

  gen:
    run: melos exec  -c 1 --scope="example" -- dart run build_runner build
