const generatedFileHeader = '''// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🤖 THIS FILE IS GENERATED AUTOMATICALLY 🤖
//
// Any changes you make here will be overwritten.
//
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// ignore_for_file: unnecessary_string_interpolations, unused_field, duplicate_import, unused_import
//
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################

''';
