// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🤖 THIS FILE IS GENERATED AUTOMATICALLY 🤖
//
// Any changes you make here will be overwritten.
//
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// ignore_for_file: unnecessary_string_interpolations, unused_field, duplicate_import, unused_import
//
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################

part of 'profile_store.dart';

class ProfileStore extends _ProfileStore {
  // constructor
  ProfileStore();

  @override
  List<Data<Object?>> get states => [profileImage];

  @override
  String? get name => 'ProfileStore';

  @override
  bool operator ==(Object other) {
    if (other is! ProfileStore) return false;

    return other.runtimeType == runtimeType &&
        failureOrNull == other.failureOrNull &&
        operationOrNull == other.operationOrNull &&
        const ListEquality().equals(
          sideEffects.all.toList(),
          other.sideEffects.all.toList(),
        ) &&
        const ListEquality().equals(states, other.states);
  }

  @override
  int get hashCode => Object.hashAll([
    failureOrNull,
    sideEffects.all,
    states,
    operationOrNull,
    runtimeType,
  ]);

  @override
  Stream<ProfileStore> get stream => streamController.stream.map((e) => this);

  @override
  Stream<ProfileStore> streamWith({
    bool skipUntilInitialized = false,
    bool skipOperations = false,
  }) {
    Stream<ProfileStore> stream = streamController.stream.map((e) => this);

    if (skipUntilInitialized) {
      stream = _streamWithSkipUntilInitialized();
    }

    if (skipOperations) {
      stream = stream.skipWhile((e) => e.hasAnyOperation);
    }

    return stream;
  }

  Stream<ProfileStore> _streamWithSkipUntilInitialized() {
    var hadSkippedEmission = false;
    final sc = StreamController<ProfileStore>(sync: true);
    StreamSubscription<bool>? streamSub;

    sc.onListen = () {
      streamSub = streamController.stream.listen((_) {
        if (isInitialized) {
          if (!sc.isClosed) sc.add(this);
        } else {
          hadSkippedEmission = true;
        }
      });

      ensureInitialized().then((_) {
        if (hadSkippedEmission && !sc.isClosed) {
          sc.add(this);
        }
      });
    };

    sc.onCancel = () => streamSub?.cancel();

    return sc.stream;
  }

  @override
  ProfileStore copy() {
    final result = ProfileStore();

    for (var i = 0; i < states.length; i++) {
      // ignore: avoid_dynamic_calls
      (result.states[i] as dynamic).updateFrom((states[i] as dynamic).copy());
    }
    result.operation = operationOrNull;
    result.failure = failureOrNull;
    result.sideEffects.clear();
    result.sideEffects.addAll(sideEffects.all);
    return result;
  }

  @override
  void updateFrom(Data<void> data) {
    // no need for calling disallowNotify(); since notifying is by default disallowed for all stores
    final old = copy();
    if (data is ProfileStore) {
      for (var i = 0; i < states.length; i++) {
        // ignore: avoid_dynamic_calls
        (states[i] as dynamic).updateFrom((data.states[i] as dynamic));
      }
    }
    value = data.valueOrNull;
    operation = data.operationOrNull;
    failure = data.failureOrNull;
    sideEffects.clear();
    sideEffects.addAll(data.sideEffects.all);

    if (old.operationOrNull != operationOrNull) {
      events.dispatch(OperationEvent(operationOrNull));
    }
    if (old.failureOrNull != failureOrNull && failureOrNull != null) {
      events.dispatch(FailureEvent(failure));
    }
    if (!const ListEquality<dynamic>().equals(
      old.sideEffects.all.toList(),
      sideEffects.all.toList(),
    )) {
      events.dispatch(SideEffectsUpdatedEvent(sideEffects.all));
    }

    publish();
  }
}
