// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🤖 THIS FILE IS GENERATED AUTOMATICALLY 🤖
//
// Any changes you make here will be overwritten.
//
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// ignore_for_file: unnecessary_string_interpolations, unused_field, duplicate_import, unused_import
//
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################

part of 'custom_side_effect.dart';

const ageDoubleKey = 'ageDoubleKey';

extension dataStringX on Data<String> {
  set age(double? value) {
    sideEffects.add(MapEntry(ageDoubleKey, value));
  }

  double? get age {
    final match = this.sideEffects.all.firstWhereOrNull(
      (e) => e is MapEntry && e.key == ageDoubleKey,
    );
    if (match != null) {
      return (match as MapEntry).value;
    } else {
      return null;
    }
  }
}
