// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🤖 THIS FILE IS GENERATED AUTOMATICALLY 🤖
//
// Any changes you make here will be overwritten.
//
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// ignore_for_file: unnecessary_string_interpolations, unused_field, duplicate_import, unused_import
//
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################

part of 'store.dart';

final $$cartItemSharedProperty = Data<CartItem>();

class GeneralStore extends _GeneralStore {
  // constructor
  GeneralStore(
    super.key, {
    required super.token,
    super.degree,
    super.withDefault = true,
  });

  @override
  final cartItem = $$cartItemSharedProperty;

  @override
  List<Data<Object?>> get states => [cartItem, user, ope];

  @override
  String? get name => 'GeneralStore';

  @override
  bool operator ==(Object other) {
    if (other is! GeneralStore) return false;

    return other.runtimeType == runtimeType &&
        failureOrNull == other.failureOrNull &&
        operationOrNull == other.operationOrNull &&
        const ListEquality().equals(
          sideEffects.all.toList(),
          other.sideEffects.all.toList(),
        ) &&
        const ListEquality().equals(states, other.states);
  }

  @override
  int get hashCode => Object.hashAll([
    failureOrNull,
    sideEffects.all,
    states,
    operationOrNull,
    runtimeType,
  ]);

  @override
  Stream<GeneralStore> get stream => streamController.stream.map((e) => this);

  @override
  Stream<GeneralStore> streamWith({
    bool skipUntilInitialized = false,
    bool skipOperations = false,
  }) {
    Stream<GeneralStore> stream = streamController.stream.map((e) => this);

    if (skipUntilInitialized) {
      stream = _streamWithSkipUntilInitialized();
    }

    if (skipOperations) {
      stream = stream.skipWhile((e) => e.hasAnyOperation);
    }

    return stream;
  }

  Stream<GeneralStore> _streamWithSkipUntilInitialized() {
    var hadSkippedEmission = false;
    final sc = StreamController<GeneralStore>(sync: true);
    StreamSubscription<bool>? streamSub;

    sc.onListen = () {
      streamSub = streamController.stream.listen((_) {
        if (isInitialized) {
          if (!sc.isClosed) sc.add(this);
        } else {
          hadSkippedEmission = true;
        }
      });

      ensureInitialized().then((_) {
        if (hadSkippedEmission && !sc.isClosed) {
          sc.add(this);
        }
      });
    };

    sc.onCancel = () => streamSub?.cancel();

    return sc.stream;
  }

  @override
  GeneralStore copy() {
    final result = GeneralStore(
      key,
      token: token,
      degree: degree,
      withDefault: withDefault,
    );

    for (var i = 0; i < states.length; i++) {
      // ignore: avoid_dynamic_calls
      (result.states[i] as dynamic).updateFrom((states[i] as dynamic).copy());
    }
    result.operation = operationOrNull;
    result.failure = failureOrNull;
    result.sideEffects.clear();
    result.sideEffects.addAll(sideEffects.all);
    return result;
  }

  @override
  void updateFrom(Data<void> data) {
    // no need for calling disallowNotify(); since notifying is by default disallowed for all stores
    final old = copy();
    if (data is GeneralStore) {
      for (var i = 0; i < states.length; i++) {
        // ignore: avoid_dynamic_calls
        (states[i] as dynamic).updateFrom((data.states[i] as dynamic));
      }
    }
    value = data.valueOrNull;
    operation = data.operationOrNull;
    failure = data.failureOrNull;
    sideEffects.clear();
    sideEffects.addAll(data.sideEffects.all);

    if (old.operationOrNull != operationOrNull) {
      events.dispatch(OperationEvent(operationOrNull));
    }
    if (old.failureOrNull != failureOrNull && failureOrNull != null) {
      events.dispatch(FailureEvent(failure));
    }
    if (!const ListEquality<dynamic>().equals(
      old.sideEffects.all.toList(),
      sideEffects.all.toList(),
    )) {
      events.dispatch(SideEffectsUpdatedEvent(sideEffects.all));
    }

    publish();
  }
}

const precisionDoubleKey = 'precisionDoubleKey';

extension dataIntX on Data<int> {
  set precision(double? value) {
    sideEffects.add(MapEntry(precisionDoubleKey, value));
  }

  double? get precision {
    final match = this.sideEffects.all.firstWhereOrNull(
      (e) => e is MapEntry && e.key == precisionDoubleKey,
    );
    if (match != null) {
      return (match as MapEntry).value;
    } else {
      return null;
    }
  }
}
