// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🤖 THIS FILE IS GENERATED AUTOMATICALLY 🤖
//
// Any changes you make here will be overwritten.
//
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// ignore_for_file: unnecessary_string_interpolations, unused_field, duplicate_import, unused_import
//
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################

part of 'form_data_test.dart';

// Generating custom form class "LoginForm"
class LoginForm extends FormData {
  LoginForm({
    required this.credentialsPageArgs,
    required this.verificationPageArgs,
  });

  // page properties
  final CredentialsPageArgs credentialsPageArgs;
  final VerificationPageArgs verificationPageArgs;

  final LoginFormContext formContext = LoginFormContext();

  @override
  String get name => 'login-form';

  @override
  late final List<FormPage> pages = [
    FormPage(
      name: 'credentials',
      items: [
        InputData<String, String>(
          name: "email",
          validator: (String? input) => credentialsPageArgs.emailInputData.validateEmail(formContext, input),
          onSubmit: (InputData<String, String> data) =>
              credentialsPageArgs.emailInputData.onSubmitEmail(formContext, data),
        ),
        InputData<String, String>(
          name: "password",
          validator: (String? input) => credentialsPageArgs.passwordInputData.validatePassword(formContext, input),
          onSubmit: (InputData<String, String> data) =>
              credentialsPageArgs.passwordInputData.onSubmitPassword(formContext, data),
        ),
      ],
    ),
    FormPage(
      name: 'verification',
      items: [
        InputData<String, int>(
          name: "code",
          validator: (String? input) => verificationPageArgs.codeInputData.validateCode(formContext, input),
          onSubmit: (InputData<String, int> data) => verificationPageArgs.codeInputData.onSubmitCode(formContext, data),
        ),
      ],
    ),
  ];

  @override
  Stream<LoginForm> get stream => streamController.stream.map((e) => this);

  @override
  LoginForm copy() => throw Exception('cannot copy a generated FormData class');

  Future<void> submitCredentialsPage() async {
    final page = pages[credentialsPageArgs.pageIndex];
    for (var inputItem in page.items) {
      if (inputItem.isOptional) {
        continue;
      }
      if (inputItem.hasNoValue) {
        await inputItem.submit();
        // if still no value return;
        if (inputItem.hasNoValue) {
          return;
        }
      }
    }

    // when all inputData items of the page have a value then submit page
    await credentialsPageArgs.onSubmitPage(
      formContext,
      credentialsPageArgs.submitResult,
      page.items[0].value,
      page.items[1].value,
    );

    if (credentialsPageArgs.submitResult.hasFailure && credentialsPageArgs.submitResult.failure.type == null) {
      credentialsPageArgs.submitResult.failure =
          credentialsPageArgs.submitResult.failure.copyWith(type: FailureType.error);
    } else if (credentialsPageArgs.submitResult.hasNoValue && !credentialsPageArgs.submitResult.hasFailure) {
      final message =
          '! No value or failure was set on submitResult data inside onSubmitPage argument callback for credentials page when it was called.';
      credentialsPageArgs.submitResult.failure = Failure(
        message,
        type: FailureType.error,
      );
      CrystallineGlobalConfig.logger.log(
        CrystallineGlobalConfig.logger.redText(message),
      );
    }
  }

  Future<void> submitVerificationPage() async {
    final page = pages[verificationPageArgs.pageIndex];
    for (var inputItem in page.items) {
      if (inputItem.isOptional) {
        continue;
      }
      if (inputItem.hasNoValue) {
        await inputItem.submit();
        // if still no value return;
        if (inputItem.hasNoValue) {
          return;
        }
      }
    }

    // when all inputData items of the page have a value then submit page
    await verificationPageArgs.onSubmitPage(
      formContext,
      verificationPageArgs.submitResult,
      page.items[0].value,
    );

    if (verificationPageArgs.submitResult.hasFailure && verificationPageArgs.submitResult.failure.type == null) {
      verificationPageArgs.submitResult.failure =
          verificationPageArgs.submitResult.failure.copyWith(type: FailureType.error);
    } else if (verificationPageArgs.submitResult.hasNoValue && !verificationPageArgs.submitResult.hasFailure) {
      final message =
          '! No value or failure was set on submitResult data inside onSubmitPage argument callback for verification page when it was called.';
      verificationPageArgs.submitResult.failure = Failure(message, type: FailureType.error);
      CrystallineGlobalConfig.logger.log(
        CrystallineGlobalConfig.logger.redText(message),
      );
    }
  }

  @override
  bool operator ==(Object other) {
    if (other is! LoginForm) return false;

    return runtimeType == other.runtimeType &&
        pages == other.pages &&
        ListEquality<InputData>().equals(items, other.items) &&
        operationOrNull == other.operationOrNull &&
        sideEffects == other.sideEffects &&
        failureOrNull == other.failureOrNull;
  }

  @override
  int get hashCode => Object.hashAll([
        pages,
        runtimeType,
        items,
        operationOrNull,
        failureOrNull,
        sideEffects.all,
      ]);
}

// custom class code for CredentialsPageArgs
class CredentialsPageArgs {
  CredentialsPageArgs({
    required this.emailInputData,
    required this.passwordInputData,
    required this.onSubmitPage,
  });

  final EmailInputData emailInputData;
  final PasswordInputData passwordInputData;
  final submitResult = Data<bool>();
  final pageIndex = 0;
  final Future<void> Function(
    LoginFormContext formContext,
    Data<bool> submitResult,
    String email,
    String password,
  ) onSubmitPage;
}

class EmailInputData {
  EmailInputData({required this.validateEmail, required this.onSubmitEmail});

  final InputValidationResult Function(
    LoginFormContext formContext,
    String? input,
  ) validateEmail;

  final Future<void> Function(
    LoginFormContext formContext,
    InputData<String, String> data,
  ) onSubmitEmail;
}

class PasswordInputData {
  PasswordInputData({
    required this.validatePassword,
    required this.onSubmitPassword,
  });

  final InputValidationResult Function(
    LoginFormContext formContext,
    String? input,
  ) validatePassword;

  final Future<void> Function(
    LoginFormContext formContext,
    InputData<String, String> data,
  ) onSubmitPassword;
}

// custom class code for VerificationPageArgs
class VerificationPageArgs {
  VerificationPageArgs({
    required this.codeInputData,
    required this.onSubmitPage,
  });

  final CodeInputData codeInputData;
  final submitResult = Data<bool>();
  final pageIndex = 1;
  final Future<void> Function(
    LoginFormContext formContext,
    Data<bool> submitResult,
    int code,
  ) onSubmitPage;
}

class CodeInputData {
  CodeInputData({required this.validateCode, required this.onSubmitCode});

  final InputValidationResult Function(
    LoginFormContext formContext,
    String? input,
  ) validateCode;

  final Future<void> Function(
    LoginFormContext formContext,
    InputData<String, int> data,
  ) onSubmitCode;
}

class LoginFormContext {}
