// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🤖 THIS FILE IS GENERATED AUTOMATICALLY 🤖
//
// Any changes you make here will be overwritten.
//
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// ignore_for_file: unnecessary_string_interpolations, unused_field, duplicate_import, unused_import
//
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################

part of 'form_data_test.dart';

// Generating custom form class "LoginForm"
class LoginForm extends FormData {
  LoginForm(
    CredentialsPage credentialsPage,
    VerificationPage verificationPage,
  ) : super(pages: [], name: 'name');

  @override
  String get name => 'super.name';

  @override
  List<FormPage> get pages => [];
}

// custom class code for CredentialsPage
class CredentialsPage {
  CredentialsPage({
    required this.emailInputData,
    required this.passwordInputData,
    required this.onSubmit,
  });

  final EmailInputData emailInputData;
  final PasswordInputData passwordInputData;
  final Future<void> Function(String email, String password) onSubmit;
}

class EmailInputData {
  EmailInputData({required this.validateEmail, required this.onSubmitEmail});

  final InputValidationResult Function(String? input) validateEmail;
  final Future<void> Function(InputData<String, String> data) onSubmitEmail;
}

class PasswordInputData {
  PasswordInputData({
    required this.validatePassword,
    required this.onSubmitPassword,
  });

  final InputValidationResult Function(String? input) validatePassword;
  final Future<void> Function(InputData<String, String> data) onSubmitPassword;
}

// custom class code for VerificationPage
class VerificationPage {
  VerificationPage({required this.codeInputData, required this.onSubmit});

  final CodeInputData codeInputData;
  final Future<void> Function(int code) onSubmit;
}

class CodeInputData {
  CodeInputData({required this.validateCode, required this.onSubmitCode});

  final InputValidationResult Function(String? input) validateCode;
  final Future<void> Function(InputData<String, int> data) onSubmitCode;
}

class LoginFormContext {}
