// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🤖 THIS FILE IS GENERATED AUTOMATICALLY 🤖
//
// Any changes you make here will be overwritten.
//
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// ignore_for_file: unnecessary_string_interpolations, unused_field, duplicate_import, unused_import
//
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################

part of 'form_data_test.dart';

// Generating custom form class "LoginForm"
class LoginForm extends FormData {
  LoginForm({
    required CredentialsPage credentialsPage,
    required VerificationPage verificationPage,
  })  : _credentialsPageArgs = credentialsPage,
        _verificationPageArgs = verificationPage;

  // page properties
  final CredentialsPage _credentialsPageArgs;
  final VerificationPage _verificationPageArgs;

  late final LoginFormContext formContext = LoginFormContext(pages);

  CredentialsContext get credentialsPage => formContext.credentialsPage;
  VerificationContext get verificationPage => formContext.verificationPage;
  @override
  late final List<FormPage> pages = [
    FormPage(
      name: 'credentials',
      items: [
        InputData<String, String>(
          name: "email",
          hint: _credentialsPageArgs.emailInputData.hint,
          value: _credentialsPageArgs.emailInputData.initialValue,
          isOptional: _credentialsPageArgs.emailInputData.isOptional,
          operation: _credentialsPageArgs.emailInputData.operation,
          failure: _credentialsPageArgs.emailInputData.failure,
          sideEffects: _credentialsPageArgs.emailInputData.sideEffects,
          validator: (String? input) => _credentialsPageArgs.emailInputData.validateEmail(formContext, input),
          onSubmit: (InputData<String, String> data) =>
              _credentialsPageArgs.emailInputData.onSubmitEmail(formContext, data),
        ),
        InputData<String, String>(
          name: "password",
          hint: _credentialsPageArgs.passwordInputData.hint,
          value: _credentialsPageArgs.passwordInputData.initialValue,
          isOptional: _credentialsPageArgs.passwordInputData.isOptional,
          operation: _credentialsPageArgs.passwordInputData.operation,
          failure: _credentialsPageArgs.passwordInputData.failure,
          sideEffects: _credentialsPageArgs.passwordInputData.sideEffects,
          validator: (String? input) => _credentialsPageArgs.passwordInputData.validatePassword(formContext, input),
          onSubmit: (InputData<String, String> data) =>
              _credentialsPageArgs.passwordInputData.onSubmitPassword(formContext, data),
        ),
      ],
    ),
    FormPage(
      name: 'verification',
      items: [
        InputData<String, int>(
          name: "code",
          hint: _verificationPageArgs.codeInputData.hint,
          value: _verificationPageArgs.codeInputData.initialValue,
          isOptional: _verificationPageArgs.codeInputData.isOptional,
          operation: _verificationPageArgs.codeInputData.operation,
          failure: _verificationPageArgs.codeInputData.failure,
          sideEffects: _verificationPageArgs.codeInputData.sideEffects,
          validator: (String? input) => _verificationPageArgs.codeInputData.validateCode(formContext, input),
          onSubmit: (InputData<String, int> data) =>
              _verificationPageArgs.codeInputData.onSubmitCode(formContext, data),
        ),
      ],
    ),
  ];

  @override
  String get name => 'login-form';

  @override
  Stream<LoginForm> get stream => streamController.stream.map((e) => this);

  @override
  LoginForm copy() => throw Exception('cannot copy a generated FormData class');

  // Satisfies [Data]'s @mustBeOverridden; behavior is [FormData.updateFrom].
  @override
  // ignore: unnecessary_overrides
  void updateFrom(Data<List<InputData<dynamic, dynamic>>> data) {
    super.updateFrom(data);
  }

  Future<void> submitCredentialsPage() async {
    final page = pages[_credentialsPageArgs.pageIndex];
    for (var inputItem in page.items) {
      if (inputItem.isOptional) {
        continue;
      }
      if (inputItem.hasNoValue) {
        await inputItem.submit();
        // if still no value return;
        if (inputItem.hasNoValue) {
          return;
        }
      }
    }

    // when all inputData items of the page have a value then submit page
    await _credentialsPageArgs.onSubmitPage(
      formContext,
      formContext.credentialsPage.submitResult,
      CredentialsPageSubmitValueArgs(page.items[0].value, page.items[1].value),
    );

    if (formContext.credentialsPage.submitResult.hasFailure &&
        formContext.credentialsPage.submitResult.failure.type == null) {
      formContext.credentialsPage.submitResult.failure =
          formContext.credentialsPage.submitResult.failure.copyWith(type: FailureType.error);
    } else if (formContext.credentialsPage.submitResult.hasNoValue &&
        !formContext.credentialsPage.submitResult.hasFailure) {
      final message =
          '! No value or failure was set on submitResult data inside onSubmitPage argument callback for credentials page when it was called.';
      formContext.credentialsPage.submitResult.failure = Failure(
        message,
        type: FailureType.error,
      );
      CrystallineGlobalConfig.logger.log(
        CrystallineGlobalConfig.logger.redText(message),
      );
    }
  }

  Future<void> submitVerificationPage() async {
    final page = pages[_verificationPageArgs.pageIndex];
    for (var inputItem in page.items) {
      if (inputItem.isOptional) {
        continue;
      }
      if (inputItem.hasNoValue) {
        await inputItem.submit();
        // if still no value return;
        if (inputItem.hasNoValue) {
          return;
        }
      }
    }

    // when all inputData items of the page have a value then submit page
    await _verificationPageArgs.onSubmitPage(
      formContext,
      formContext.verificationPage.submitResult,
      VerificationPageSubmitValueArgs(page.items[0].value),
    );

    if (formContext.verificationPage.submitResult.hasFailure &&
        formContext.verificationPage.submitResult.failure.type == null) {
      formContext.verificationPage.submitResult.failure =
          formContext.verificationPage.submitResult.failure.copyWith(type: FailureType.error);
    } else if (formContext.verificationPage.submitResult.hasNoValue &&
        !formContext.verificationPage.submitResult.hasFailure) {
      final message =
          '! No value or failure was set on submitResult data inside onSubmitPage argument callback for verification page when it was called.';
      formContext.verificationPage.submitResult.failure = Failure(
        message,
        type: FailureType.error,
      );
      CrystallineGlobalConfig.logger.log(
        CrystallineGlobalConfig.logger.redText(message),
      );
    }
  }

  @override
  Future submit({
    bool reSubmitCredentialsPage = false,
    bool reSubmitVerificationPage = false,
  }) async {
    if (formContext.credentialsPage.submitResult.hasNoValue || reSubmitCredentialsPage) {
      await submitCredentialsPage();
      if (formContext.credentialsPage.submitResult.hasFailure) {
        return;
      }
    }

    if (formContext.verificationPage.submitResult.hasNoValue || reSubmitVerificationPage) {
      await submitVerificationPage();
      if (formContext.verificationPage.submitResult.hasFailure) {
        return;
      }
    }
  }

  @override
  bool operator ==(Object other) {
    if (other is! LoginForm) return false;

    return runtimeType == other.runtimeType &&
        pages == other.pages &&
        ListEquality<InputData>().equals(items, other.items) &&
        operationOrNull == other.operationOrNull &&
        sideEffects == other.sideEffects &&
        failureOrNull == other.failureOrNull;
  }

  @override
  int get hashCode => Object.hashAll([
        pages,
        runtimeType,
        items,
        operationOrNull,
        failureOrNull,
        sideEffects.all,
      ]);
}

// custom class code for CredentialsPage
class CredentialsPage {
  CredentialsPage({
    required this.emailInputData,
    required this.passwordInputData,
    required this.onSubmitPage,
  });

  final EmailInputData emailInputData;
  final PasswordInputData passwordInputData;
  final pageIndex = 0;
  final Future<void> Function(
    LoginFormContext formContext,
    Data<bool> submitResult,
    CredentialsPageSubmitValueArgs args,
  ) onSubmitPage;
}

class EmailInputData {
  EmailInputData({
    required this.validateEmail,
    required this.onSubmitEmail,
    this.isOptional = false,
    this.hint,
    this.initialValue,
    this.operation,
    this.failure,
    this.sideEffects,
  });

  final Operation? operation;
  final Failure? failure;
  final List<dynamic>? sideEffects;
  final bool isOptional;
  final String? hint;
  final String? initialValue;
  final InputValidationResult Function(
    LoginFormContext formContext,
    String? input,
  ) validateEmail;
  final Future<void> Function(
    LoginFormContext formContext,
    InputData<String, String> data,
  ) onSubmitEmail;
}

class PasswordInputData {
  PasswordInputData({
    required this.validatePassword,
    required this.onSubmitPassword,
    this.isOptional = false,
    this.hint,
    this.initialValue,
    this.operation,
    this.failure,
    this.sideEffects,
  });

  final Operation? operation;
  final Failure? failure;
  final List<dynamic>? sideEffects;
  final bool isOptional;
  final String? hint;
  final String? initialValue;
  final InputValidationResult Function(
    LoginFormContext formContext,
    String? input,
  ) validatePassword;
  final Future<void> Function(
    LoginFormContext formContext,
    InputData<String, String> data,
  ) onSubmitPassword;
}

// custom class code for VerificationPage
class VerificationPage {
  VerificationPage({required this.codeInputData, required this.onSubmitPage});

  final CodeInputData codeInputData;
  final pageIndex = 1;
  final Future<void> Function(
    LoginFormContext formContext,
    Data<bool> submitResult,
    VerificationPageSubmitValueArgs args,
  ) onSubmitPage;
}

class CodeInputData {
  CodeInputData({
    required this.validateCode,
    required this.onSubmitCode,
    this.isOptional = false,
    this.hint,
    this.initialValue,
    this.operation,
    this.failure,
    this.sideEffects,
  });

  final Operation? operation;
  final Failure? failure;
  final List<dynamic>? sideEffects;
  final bool isOptional;
  final String? hint;
  final int? initialValue;
  final InputValidationResult Function(
    LoginFormContext formContext,
    String? input,
  ) validateCode;
  final Future<void> Function(
    LoginFormContext formContext,
    InputData<String, int> data,
  ) onSubmitCode;
}

class CredentialsContext {
  CredentialsContext(this._pages, this.index);
  final List<FormPage> _pages;
  final int index;

  final submitResult = Data<bool>();

  InputData<String, String> get email => _pages[index].items[0] as InputData<String, String>;
  InputData<String, String> get password => _pages[index].items[1] as InputData<String, String>;
}

class VerificationContext {
  VerificationContext(this._pages, this.index);
  final List<FormPage> _pages;
  final int index;

  final submitResult = Data<bool>();

  InputData<String, int> get code => _pages[index].items[0] as InputData<String, int>;
}

class CredentialsPageSubmitValueArgs {
  CredentialsPageSubmitValueArgs(this.email, this.password);

  final String email;
  final String password;
}

class VerificationPageSubmitValueArgs {
  VerificationPageSubmitValueArgs(this.code);

  final int code;
}

class LoginFormContext {
  LoginFormContext(this._pages);
  final List<FormPage> _pages;

  late final credentialsPage = CredentialsContext(_pages, 0);
  late final verificationPage = VerificationContext(_pages, 1);
}

// Generating custom form class "EditProfileForm"
class EditProfileForm extends FormData {
  EditProfileForm({required ProfilePage profilePage}) : _profilePageArgs = profilePage;

  // page properties
  final ProfilePage _profilePageArgs;

  late final EditProfileFormContext formContext = EditProfileFormContext(pages);

  InputData<String, String> get displayName => formContext.profilePage.displayName;
  InputData<String, String> get bio => formContext.profilePage.bio;
  Data<bool> get submitResult => formContext.profilePage.submitResult;

  @override
  late final List<FormPage> pages = [
    FormPage(
      name: 'profile',
      items: [
        InputData<String, String>(
          name: "displayName",
          hint: _profilePageArgs.displayNameInputData.hint,
          value: _profilePageArgs.displayNameInputData.initialValue,
          isOptional: _profilePageArgs.displayNameInputData.isOptional,
          operation: _profilePageArgs.displayNameInputData.operation,
          failure: _profilePageArgs.displayNameInputData.failure,
          sideEffects: _profilePageArgs.displayNameInputData.sideEffects,
          validator: (String? input) => _profilePageArgs.displayNameInputData.validateDisplayName(formContext, input),
          onSubmit: (InputData<String, String> data) =>
              _profilePageArgs.displayNameInputData.onSubmitDisplayName(formContext, data),
        ),
        InputData<String, String>(
          name: "bio",
          hint: _profilePageArgs.bioInputData.hint,
          value: _profilePageArgs.bioInputData.initialValue,
          isOptional: _profilePageArgs.bioInputData.isOptional,
          operation: _profilePageArgs.bioInputData.operation,
          failure: _profilePageArgs.bioInputData.failure,
          sideEffects: _profilePageArgs.bioInputData.sideEffects,
          validator: (String? input) => _profilePageArgs.bioInputData.validateBio(formContext, input),
          onSubmit: (InputData<String, String> data) => _profilePageArgs.bioInputData.onSubmitBio(formContext, data),
        ),
      ],
    ),
  ];

  @override
  String get name => 'edit-profile-form';

  @override
  Stream<EditProfileForm> get stream => streamController.stream.map((e) => this);

  @override
  EditProfileForm copy() => throw Exception('cannot copy a generated FormData class');

  // Satisfies [Data]'s @mustBeOverridden; behavior is [FormData.updateFrom].
  @override
  // ignore: unnecessary_overrides
  void updateFrom(Data<List<InputData<dynamic, dynamic>>> data) {
    super.updateFrom(data);
  }

  Future<void> _submitProfilePage() async {
    final page = pages[_profilePageArgs.pageIndex];
    for (var inputItem in page.items) {
      if (inputItem.isOptional) {
        continue;
      }
      if (inputItem.hasNoValue) {
        await inputItem.submit();
        // if still no value return;
        if (inputItem.hasNoValue) {
          return;
        }
      }
    }

    // when all inputData items of the page have a value then submit page
    await _profilePageArgs.onSubmitPage(
      formContext,
      formContext.profilePage.submitResult,
      ProfilePageSubmitValueArgs(page.items[0].value, page.items[1].value),
    );

    if (formContext.profilePage.submitResult.hasFailure && formContext.profilePage.submitResult.failure.type == null) {
      formContext.profilePage.submitResult.failure =
          formContext.profilePage.submitResult.failure.copyWith(type: FailureType.error);
    } else if (formContext.profilePage.submitResult.hasNoValue && !formContext.profilePage.submitResult.hasFailure) {
      final message =
          '! No value or failure was set on submitResult data inside onSubmitPage argument callback for profile page when it was called.';
      formContext.profilePage.submitResult.failure = Failure(
        message,
        type: FailureType.error,
      );
      CrystallineGlobalConfig.logger.log(
        CrystallineGlobalConfig.logger.redText(message),
      );
    }
  }

  @override
  Future submit() async {
    await _submitProfilePage();
  }

  @override
  bool operator ==(Object other) {
    if (other is! EditProfileForm) return false;

    return runtimeType == other.runtimeType &&
        pages == other.pages &&
        ListEquality<InputData>().equals(items, other.items) &&
        operationOrNull == other.operationOrNull &&
        sideEffects == other.sideEffects &&
        failureOrNull == other.failureOrNull;
  }

  @override
  int get hashCode => Object.hashAll([
        pages,
        runtimeType,
        items,
        operationOrNull,
        failureOrNull,
        sideEffects.all,
      ]);
}

// custom class code for ProfilePage
class ProfilePage {
  ProfilePage({
    required this.displayNameInputData,
    required this.bioInputData,
    required this.onSubmitPage,
  });

  final DisplayNameInputData displayNameInputData;
  final BioInputData bioInputData;
  final pageIndex = 0;
  final Future<void> Function(
    EditProfileFormContext formContext,
    Data<bool> submitResult,
    ProfilePageSubmitValueArgs args,
  ) onSubmitPage;
}

class DisplayNameInputData {
  DisplayNameInputData({
    required this.validateDisplayName,
    required this.onSubmitDisplayName,
    this.isOptional = false,
    this.hint,
    this.initialValue,
    this.operation,
    this.failure,
    this.sideEffects,
  });

  final Operation? operation;
  final Failure? failure;
  final List<dynamic>? sideEffects;
  final bool isOptional;
  final String? hint;
  final String? initialValue;
  final InputValidationResult Function(
    EditProfileFormContext formContext,
    String? input,
  ) validateDisplayName;
  final Future<void> Function(
    EditProfileFormContext formContext,
    InputData<String, String> data,
  ) onSubmitDisplayName;
}

class BioInputData {
  BioInputData({
    required this.validateBio,
    required this.onSubmitBio,
    this.isOptional = false,
    this.hint,
    this.initialValue,
    this.operation,
    this.failure,
    this.sideEffects,
  });

  final Operation? operation;
  final Failure? failure;
  final List<dynamic>? sideEffects;
  final bool isOptional;
  final String? hint;
  final String? initialValue;
  final InputValidationResult Function(
    EditProfileFormContext formContext,
    String? input,
  ) validateBio;
  final Future<void> Function(
    EditProfileFormContext formContext,
    InputData<String, String> data,
  ) onSubmitBio;
}

class ProfileContext {
  ProfileContext(this._pages, this.index);
  final List<FormPage> _pages;
  final int index;

  final submitResult = Data<bool>();

  InputData<String, String> get displayName => _pages[index].items[0] as InputData<String, String>;
  InputData<String, String> get bio => _pages[index].items[1] as InputData<String, String>;
}

class ProfilePageSubmitValueArgs {
  ProfilePageSubmitValueArgs(this.displayName, this.bio);

  final String displayName;
  final String bio;
}

class EditProfileFormContext {
  EditProfileFormContext(this._pages);
  final List<FormPage> _pages;

  late final profilePage = ProfileContext(_pages, 0);
}
