// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🤖 THIS FILE IS GENERATED AUTOMATICALLY 🤖
//
// Any changes you make here will be overwritten.
//
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// 🚫🚫🚫 DO NOT EDIT THIS FILE 🚫🚫🚫
// ignore_for_file: unnecessary_string_interpolations, unused_field, duplicate_import, unused_import
//
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################
// ####################################################################################

part of 'cart_store.dart';

class CartStore extends _CartStore {
  // constructor
  CartStore();

  @override
  List<Data<Object?>> get states => [cartItems];

  @override
  String? get name => 'CartStore';

  @override
  bool operator ==(Object other) {
    if (other is! CartStore) return false;

    return other.runtimeType == runtimeType &&
        failureOrNull == other.failureOrNull &&
        operationOrNull == other.operationOrNull &&
        const ListEquality().equals(
          sideEffects.all.toList(),
          other.sideEffects.all.toList(),
        ) &&
        const ListEquality().equals(states, other.states);
  }

  @override
  int get hashCode =>
      (failureOrNull?.hashCode ?? 9) +
      sideEffects.all.hashCode +
      states.hashCode +
      (operationOrNull?.hashCode ?? 14) +
      runtimeType.hashCode;

  @override
  Stream<CartStore> get stream => streamController.stream.map((e) => this);

  @override
  Stream<CartStore> streamWith({
    bool skipUntilInitialized = false,
    bool skipOperations = false,
  }) {
    Stream<CartStore> stream = streamController.stream.map((e) => this);

    if (skipUntilInitialized) {
      stream = _streamWithSkipUntilInitialized();
    }

    if (skipOperations) {
      stream = stream.skipWhile((e) => e.hasAnyOperation);
    }

    return stream;
  }

  Stream<CartStore> _streamWithSkipUntilInitialized() {
    var hadSkippedEmission = false;
    final sc = StreamController<CartStore>(sync: true);
    StreamSubscription<bool>? streamSub;

    sc.onListen = () {
      streamSub = streamController.stream.listen((_) {
        if (isInitialized) {
          if (!sc.isClosed) sc.add(this);
        } else {
          hadSkippedEmission = true;
        }
      });

      ensureInitialized().then((_) {
        if (hadSkippedEmission && !sc.isClosed) {
          sc.add(this);
        }
      });
    };

    sc.onCancel = () => streamSub?.cancel();

    return sc.stream;
  }
}
