name: Test

on:
  push:
    branches: [main, test/**, fix/**]
  pull_request:
    branches: [main, test/**, fix/**]
jobs:
  test:
    name: "${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        sdk: [stable]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.10.4"
          channel: "stable"

      - name: Install melos
        run: dart pub global activate melos 3.0.1

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed lib/ test/

      - name: Run all melos scripts
        run: melos all
