name: Test

on:
  push:
    branches: [master, test/**, fix/**]
  pull_request:
    branches: [master, test/**, fix/**]
jobs:
  test:
    name: "${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        sdk: [stable]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install melos
        run: dart pub global activate melos 3.0.1

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed lib/ test/

      - name: Run all melos scripts
        run: melos all
